// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntipynxrnntsvaqvzcpc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50aXB5bnhybm50c3ZhcXZ6Y3BjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MTc2MDMsImV4cCI6MjA1Nzk5MzYwM30.YrhKyMBV7bARP4BH_0OKyQ2qY6ArHj90puDPVIUO2KM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);